// All fake content for the app. Words inside posts are marked as [[key]] or
// [[key|shown form]]; every key must exist in VOCAB.
// level: 1 = Easy, 2 = Medium, 3 = Hard.

window.CHARACTERS = {
  zorp: { name: "Zorp", handle: "alien_intern", avatar: "👽", color: "#7ee081", lang: "en", bio: "Intern from Kepler-442b. Studying humans. Please do not dissect me." },
  whiskers: { name: "Mr. Whiskers", handle: "cat_ceo", avatar: "🐱", color: "#f6b26b", lang: "en", bio: "CEO of Box Inc. I knock things off tables professionally." },
  captain: { name: "Captain Procrastinate", handle: "captain_later", avatar: "⛵", color: "#6fa8dc", lang: "mix", bio: "大學生 / professional deadline surfer 🏄" },
  grandma: { name: "Grandma Wi-Fi", handle: "grandma_wifi", avatar: "👵", color: "#e691b8", lang: "mix", bio: "72 歲 learning the internet. Grandson says I use too many emojis 🙏🌸" },
  fern: { name: "Fern the Fern", handle: "fern_feelings", avatar: "🌿", color: "#57bb8a", lang: "en", bio: "A houseplant with opinions. Photosynthesis enthusiast." },
  pigeon: { name: "Plato the Pigeon", handle: "philosopher_pigeon", avatar: "🐦", color: "#a4a4c1", lang: "en", bio: "Thinker. Statue sitter. Accepts payment in bread." },
  socrates: { name: "Gym Socrates", handle: "gym_socrates", avatar: "💪", color: "#e06666", lang: "en", bio: "The unexamined workout is not worth lifting." },
  reginald: { name: "Sir Reginald", handle: "time_traveler_1885", avatar: "🎩", color: "#b4a7d6", lang: "en", bio: "Gentleman from 1885. Accidentally arrived in your century." },
  fizz: { name: "Dr. Fizz", handle: "mad_scientist", avatar: "🧪", color: "#76d7ea", lang: "en", bio: "Chemist. 14 explosions this year (a personal record)." },
  pablo: { name: "Pablo the Penguin", handle: "penguin_problems", avatar: "🐧", color: "#9fc5e8", lang: "en", bio: "Antarctica. My iceberg is shrinking. Ask me why." },
  chefbot: { name: "ChefBot 3000", handle: "angry_chef_bot", avatar: "👨‍🍳", color: "#ffd966", lang: "en", bio: "Culinary robot. Zero tolerance for bad pizza." },
  llama: { name: "Drama Llama", handle: "drama_llama", avatar: "🦙", color: "#d5a6bd", lang: "mix", bio: "藝術系 / everything is a tragedy 💅" },
  ann: { name: "Ann in Boston", handle: "ann_studyabroad", avatar: "🎓", color: "#93c47d", lang: "mix", bio: "台灣留學生 in Boston 🇹🇼➡️🇺🇸 surviving one culture shock at a time" }
};

window.VOCAB = {
  indispensable: { pos: "adj.", zh: "不可或缺的", level: 2, ex: "A good dictionary is indispensable for learning a new language.", exZh: "好的字典對學習新語言來說是不可或缺的。" },
  ubiquitous: { pos: "adj.", zh: "無所不在的", level: 3, ex: "Smartphones have become ubiquitous in modern life.", exZh: "智慧型手機在現代生活中已經無所不在。" },
  deteriorate: { pos: "v.", zh: "惡化；變差", level: 2, ex: "His health began to deteriorate after he stopped exercising.", exZh: "他停止運動後，健康開始惡化。" },
  allocate: { pos: "v.", zh: "分配；撥出（資源）", level: 2, ex: "The school will allocate more money to the library next year.", exZh: "學校明年會撥更多經費給圖書館。" },
  arbitrary: { pos: "adj.", zh: "任意的；武斷的", level: 2, ex: "The teacher's grading seemed completely arbitrary.", exZh: "那位老師的評分方式看起來完全很隨意。" },
  procrastinate: { pos: "v.", zh: "拖延", level: 1, ex: "If you procrastinate, the work will only get harder.", exZh: "如果你拖延，工作只會變得更難。" },
  inevitable: { pos: "adj.", zh: "不可避免的", level: 1, ex: "Change is inevitable, so we should learn to accept it.", exZh: "改變是不可避免的，所以我們應該學會接受。" },
  ambiguous: { pos: "adj.", zh: "模稜兩可的；含糊的", level: 2, ex: "The question was ambiguous, so students answered it in different ways.", exZh: "這個問題模稜兩可，所以學生們的回答各不相同。" },
  skeptical: { pos: "adj.", zh: "懷疑的", level: 1, ex: "Scientists were skeptical of the new theory at first.", exZh: "科學家們一開始對這個新理論抱持懷疑。" },
  elaborate: { pos: "adj.", zh: "精心製作的；複雜的", level: 2, ex: "She made an elaborate plan for the school festival.", exZh: "她為校慶做了一份精心的計畫。" },
  substantial: { pos: "adj.", zh: "大量的；可觀的", level: 1, ex: "The company made a substantial profit this year.", exZh: "這家公司今年獲得了可觀的利潤。" },
  contemplate: { pos: "v.", zh: "沉思；仔細考慮", level: 2, ex: "He sat by the lake to contemplate his future.", exZh: "他坐在湖邊思考自己的未來。" },
  profound: { pos: "adj.", zh: "深刻的；深遠的", level: 2, ex: "The book had a profound effect on how I see the world.", exZh: "這本書深刻地影響了我看世界的方式。" },
  hypothesis: { pos: "n.", zh: "假設；假說", level: 1, ex: "The experiment was designed to test the hypothesis.", exZh: "這個實驗是為了驗證那個假設而設計的。" },
  adapt: { pos: "v.", zh: "適應；調整", level: 1, ex: "Animals must adapt to changes in their environment.", exZh: "動物必須適應環境的變化。" },
  compelling: { pos: "adj.", zh: "令人信服的；強有力的", level: 2, ex: "The lawyer presented compelling evidence to the jury.", exZh: "律師向陪審團提出了令人信服的證據。" },
  phenomenon: { pos: "n.", zh: "現象", level: 1, ex: "A rainbow is a natural phenomenon caused by light and water.", exZh: "彩虹是由光和水造成的自然現象。" },
  obsolete: { pos: "adj.", zh: "過時的；淘汰的", level: 2, ex: "Fax machines are almost obsolete today.", exZh: "傳真機如今幾乎已經被淘汰了。" },
  catalyst: { pos: "n.", zh: "催化劑；促成因素", level: 3, ex: "The invention of the printing press was a catalyst for social change.", exZh: "印刷術的發明是社會變革的催化劑。" },
  volatile: { pos: "adj.", zh: "不穩定的；易揮發的", level: 3, ex: "The stock market has been very volatile this month.", exZh: "這個月股市非常不穩定。" },
  erode: { pos: "v.", zh: "侵蝕；逐漸削弱", level: 3, ex: "Over centuries, the river eroded the rock and formed a canyon.", exZh: "數百年來，河水侵蝕岩石，形成了峽谷。" },
  mitigate: { pos: "v.", zh: "減輕；緩和", level: 3, ex: "Planting trees can help mitigate the effects of air pollution.", exZh: "種樹有助於減輕空氣污染的影響。" },
  inadequate: { pos: "adj.", zh: "不足的；不夠格的", level: 1, ex: "The food supply was inadequate for the growing population.", exZh: "糧食供應不足以應付不斷增加的人口。" },
  vague: { pos: "adj.", zh: "模糊的；不明確的", level: 1, ex: "His answer was so vague that nobody understood it.", exZh: "他的回答太模糊，沒有人聽得懂。" },
  exasperated: { pos: "adj.", zh: "惱怒的；極度不耐煩的", level: 3, ex: "The exasperated teacher asked the class to be quiet for the fifth time.", exZh: "被惹惱的老師第五次要求全班安靜。" },
  irreversible: { pos: "adj.", zh: "不可逆的；無法挽回的", level: 2, ex: "Some damage to the environment is irreversible.", exZh: "有些對環境造成的破壞是無法挽回的。" },
  turbulent: { pos: "adj.", zh: "動盪的；混亂的", level: 2, ex: "The country went through a turbulent period after the war.", exZh: "這個國家在戰後經歷了一段動盪時期。" },
  verbose: { pos: "adj.", zh: "冗長的；囉嗦的", level: 3, ex: "Try not to be verbose in the TOEFL writing section.", exZh: "托福寫作時盡量不要寫得太冗長。" },
  meticulous: { pos: "adj.", zh: "一絲不苟的；極仔細的", level: 2, ex: "She is meticulous about checking her essays for mistakes.", exZh: "她檢查作文錯誤時非常一絲不苟。" },
  industrious: { pos: "adj.", zh: "勤勉的；勤奮的", level: 3, ex: "Ants are known as industrious insects.", exZh: "螞蟻以勤勞的昆蟲著稱。" },
  frugal: { pos: "adj.", zh: "節儉的", level: 3, ex: "Being frugal helped him save money for studying abroad.", exZh: "節儉讓他存到了出國留學的錢。" },
  wary: { pos: "adj.", zh: "小心提防的；謹慎的", level: 2, ex: "Be wary of websites that ask for your password.", exZh: "要提防那些要求你輸入密碼的網站。" },
  acknowledge: { pos: "v.", zh: "承認；致謝；表示收到", level: 1, ex: "He finally acknowledged that he had made a mistake.", exZh: "他終於承認自己犯了錯。" },
  abundant: { pos: "adj.", zh: "豐富的；充足的", level: 1, ex: "Fish are abundant in this part of the ocean.", exZh: "這片海域的魚類非常豐富。" },
  thrive: { pos: "v.", zh: "茁壯成長；興盛", level: 2, ex: "These plants thrive in warm, wet climates.", exZh: "這些植物在溫暖潮濕的氣候中生長茂盛。" },
  inconsistent: { pos: "adj.", zh: "不一致的；前後矛盾的", level: 1, ex: "The witness gave inconsistent answers to the police.", exZh: "那名證人給警方的回答前後矛盾。" },
  perplexing: { pos: "adj.", zh: "令人困惑的", level: 2, ex: "The disappearance of the ancient city is still a perplexing mystery.", exZh: "那座古城的消失至今仍是令人困惑的謎。" },
  unprecedented: { pos: "adj.", zh: "前所未有的", level: 2, ex: "The city experienced an unprecedented heat wave last summer.", exZh: "這座城市去年夏天經歷了前所未有的熱浪。" },
  sedentary: { pos: "adj.", zh: "久坐不動的", level: 3, ex: "A sedentary lifestyle can lead to health problems.", exZh: "久坐不動的生活方式可能導致健康問題。" },
  evade: { pos: "v.", zh: "逃避；躲避", level: 2, ex: "The politician tried to evade the reporter's question.", exZh: "那位政治人物試圖迴避記者的問題。" },
  admirable: { pos: "adj.", zh: "令人欽佩的", level: 1, ex: "Her patience with the children is admirable.", exZh: "她對孩子們的耐心令人欽佩。" },
  symbiosis: { pos: "n.", zh: "共生（關係）", level: 3, ex: "Clownfish and sea anemones live in symbiosis.", exZh: "小丑魚和海葵是共生關係。" },
  relentless: { pos: "adj.", zh: "無情的；堅持不懈的", level: 3, ex: "The relentless rain lasted for a week.", exZh: "毫不停歇的大雨下了一整個星期。" },
  concise: { pos: "adj.", zh: "簡潔的；簡明的", level: 1, ex: "Please write a concise summary of the lecture.", exZh: "請寫一份簡明的課堂摘要。" },
  reluctant: { pos: "adj.", zh: "不情願的", level: 1, ex: "He was reluctant to speak in front of the class.", exZh: "他不太願意在全班面前說話。" },
  moderate: { pos: "adj.", zh: "適度的；中等的", level: 1, ex: "Moderate exercise is good for your heart.", exZh: "適度運動對心臟有益。" },
  scrutinize: { pos: "v.", zh: "仔細檢查；詳細審查", level: 3, ex: "The professor scrutinized every source in my paper.", exZh: "教授仔細檢查了我論文中的每一個引用來源。" },
  vulnerable: { pos: "adj.", zh: "脆弱的；易受傷害的", level: 2, ex: "Young children are especially vulnerable to the flu.", exZh: "幼童特別容易感染流感。" },
  resilient: { pos: "adj.", zh: "有韌性的；能迅速恢復的", level: 2, ex: "Coral reefs can be surprisingly resilient if pollution is reduced.", exZh: "只要減少污染，珊瑚礁的恢復力可能出乎意料地強。" },
  deliberate: { pos: "adj.", zh: "故意的；深思熟慮的", level: 2, ex: "It was not an accident; it was a deliberate choice.", exZh: "那不是意外，而是刻意的選擇。" },
  tolerate: { pos: "v.", zh: "容忍；忍受", level: 1, ex: "Some plants can tolerate very cold weather.", exZh: "有些植物能忍受非常寒冷的天氣。" },
  provoke: { pos: "v.", zh: "激怒；引起", level: 2, ex: "The article provoked a heated debate online.", exZh: "那篇文章在網路上引發了激烈的辯論。" },
  ephemeral: { pos: "adj.", zh: "短暫的；轉瞬即逝的", level: 3, ex: "Fame on social media is often ephemeral.", exZh: "社群媒體上的名氣往往轉瞬即逝。" },
  exorbitant: { pos: "adj.", zh: "（價格）過高的；離譜的", level: 3, ex: "The hotel charged an exorbitant price for breakfast.", exZh: "那家飯店的早餐價格貴得離譜。" },
  ritual: { pos: "n.", zh: "儀式；例行公事", level: 1, ex: "Drinking tea every morning is my daily ritual.", exZh: "每天早上喝茶是我的例行儀式。" },
  bizarre: { pos: "adj.", zh: "怪異的；奇特的", level: 1, ex: "I had a bizarre dream about a talking fish.", exZh: "我做了一個關於會說話的魚的怪夢。" },
  assimilate: { pos: "v.", zh: "同化；融入；吸收", level: 3, ex: "Immigrants often assimilate into a new culture over time.", exZh: "移民通常會隨著時間融入新的文化。" },
  reciprocal: { pos: "adj.", zh: "互惠的；相互的", level: 3, ex: "The two schools have a reciprocal exchange program.", exZh: "這兩所學校有互惠的交換計畫。" },
  ample: { pos: "adj.", zh: "充足的；大量的", level: 2, ex: "You will have ample time to finish the test.", exZh: "你會有充足的時間完成考試。" },
  endure: { pos: "v.", zh: "忍受；持續", level: 1, ex: "The explorers had to endure extreme cold.", exZh: "探險家們必須忍受極度的寒冷。" },
  lucrative: { pos: "adj.", zh: "賺錢的；有利可圖的", level: 3, ex: "He left his lucrative job to become a teacher.", exZh: "他辭掉了高薪的工作去當老師。" },
  efficiency: { pos: "n.", zh: "效率", level: 1, ex: "New technology has improved the efficiency of factories.", exZh: "新科技提升了工廠的效率。" },
  nostalgia: { pos: "n.", zh: "懷舊；思鄉之情", level: 2, ex: "Old songs fill my grandparents with nostalgia.", exZh: "老歌讓我的祖父母充滿懷舊之情。" },
  persistent: { pos: "adj.", zh: "堅持不懈的；持續的", level: 1, ex: "Persistent practice is the key to a high TOEFL score.", exZh: "持續不懈的練習是托福高分的關鍵。" },
  accumulate: { pos: "v.", zh: "累積；積聚", level: 1, ex: "Dust accumulates quickly if you don't clean your room.", exZh: "如果你不打掃房間，灰塵會很快累積。" }
};

window.POSTS = [
  { id: "p1", author: "zorp", time: "2m", topic: "Astronomy", likes: 842, replies: 57,
    text: "Day 12 on Earth. Your planet orbits ONE medium-sized star and you act like it's special. On my planet we have three suns, so sunscreen is [[indispensable]].\n\nAlso, coffee is [[ubiquitous]] here. Without it, humans [[deteriorate]] rapidly after 3 p.m. Fascinating species. 👽☕",
    zh: "來地球第 12 天。你們的星球只繞著「一顆」中等大小的恆星轉，還覺得它很特別。我的星球有三個太陽，所以防曬乳是不可或缺的。\n\n另外，咖啡在這裡無所不在。沒有咖啡，人類下午三點後就會迅速變差。真是迷人的物種。👽☕" },
  { id: "p2", author: "whiskers", time: "9m", topic: "Business", likes: 2310, replies: 188,
    text: "Board meeting update: I have decided to [[allocate]] 90% of the company budget to cardboard boxes.\n\nWhen the CFO asked why, I knocked his pen off the table. The decision is final and completely [[arbitrary]]. Meeting adjourned. 🐾",
    zh: "董事會更新：我決定把公司 90% 的預算撥給紙箱。\n\n財務長問為什麼，我就把他的筆從桌上撥下去。這個決定是最終的，而且完全是隨意的。散會。🐾" },
  { id: "p3", author: "captain", time: "14m", topic: "Campus Life", likes: 1567, replies: 203,
    text: "欸 guys，I planned to [[procrastinate]] for only 5 minutes. That was in 2019.\n\nThe report is due tomorrow and failure feels [[inevitable]] at this point 🫠 但我先去煮個泡麵",
    zh: "欸大家，我原本打算只拖延 5 分鐘。那是 2019 年的事。\n\n報告明天要交，到這個地步失敗感覺是無法避免的 🫠 但我先去煮個泡麵。" },
  { id: "p4", author: "grandma", time: "21m", topic: "Tech", likes: 3902, replies: 412,
    text: "My grandson says my posts are [[ambiguous]]. I wrote \"LOL\" under a funeral photo 😭 我以為是 Lots Of Love 啊！\n\nNow everyone is [[skeptical]] of my sympathy. 年輕人的網路好難 🙏🌸",
    zh: "我孫子說我的貼文很模稜兩可。我在一張喪禮照片下面留言「LOL」😭 我以為是 Lots Of Love 啊！\n\n現在大家都懷疑我的同情心是不是真的。年輕人的網路好難 🙏🌸" },
  { id: "p5", author: "fern", time: "33m", topic: "Biology", likes: 1120, replies: 76,
    text: "Dear human, I do not need an [[elaborate]] watering schedule. I need ONE glass of water per week.\n\nInstead you give me a [[substantial]] flood every day and act surprised when my roots rot. Photosynthesis is not a swimming competition. 🥲",
    zh: "親愛的人類，我不需要精心設計的澆水計畫。我一週只需要「一杯」水。\n\n結果你每天給我一場大洪水，然後在我根部腐爛時一臉驚訝。光合作用不是游泳比賽。🥲" },
  { id: "p6", author: "pigeon", time: "47m", topic: "Philosophy", likes: 998, replies: 64,
    text: "I [[contemplate]] the meaning of life while standing on a statue's head. Humans call this \"loitering.\"\n\nI call it a [[profound]] career choice. The statue has not complained.",
    zh: "我站在雕像頭上思考人生的意義。人類把這叫做「閒晃」。\n\n我稱之為一個深刻的職涯選擇。雕像從來沒抱怨過。" },
  { id: "p7", author: "socrates", time: "1h", topic: "Health", likes: 1804, replies: 139,
    text: "Skipping leg day is not laziness. It is a [[hypothesis]]: that my legs will simply [[adapt]] on their own.\n\nAfter six months, the evidence against it is [[compelling]]. I now walk like a coat hanger.",
    zh: "不練腿不是懶惰，而是一個假設：我的腿會自己適應。\n\n六個月後，反駁這個假設的證據非常有說服力。我現在走路像一個衣架。" },
  { id: "p8", author: "reginald", time: "1h", topic: "History", likes: 2745, replies: 221,
    text: "Arrived from 1885. Your \"smartphones\" are a remarkable [[phenomenon]]: an entire train of people staring at glowing rectangles in total silence, like monks.\n\nMy pocket watch is now [[obsolete]]. So, apparently, am I. 🎩",
    zh: "從 1885 年抵達。你們的「智慧型手機」是個非凡的現象：整列火車的人在完全的寂靜中盯著發光的長方形，像修道士一樣。\n\n我的懷錶現在過時了。顯然，我也是。🎩" },
  { id: "p9", author: "fizz", time: "2h", topic: "Chemistry", likes: 654, replies: 48,
    text: "Lab update: I tried to prove that coffee is a [[catalyst]] for productivity.\n\nResult: I reorganized my sock drawer 4 times and wrote zero pages. The reaction was fast but extremely [[volatile]]. More data needed. ☕🧪",
    zh: "實驗室更新：我試圖證明咖啡是生產力的催化劑。\n\n結果：我整理了襪子抽屜 4 次，一頁都沒寫。反應很快，但極度不穩定。需要更多數據。☕🧪" },
  { id: "p10", author: "pablo", time: "2h", topic: "Environment", likes: 4120, replies: 356,
    text: "My iceberg used to be the size of a parking lot. Now it's the size of a yoga mat.\n\nRising temperatures continue to [[erode]] my neighborhood. Humans, please [[mitigate]] your emissions. I am tired of standing on one foot. 🐧",
    zh: "我的冰山以前有一個停車場那麼大，現在只剩瑜伽墊那麼大。\n\n不斷上升的氣溫持續侵蝕我的社區。人類，請減少你們的排放。我已經厭倦用單腳站立了。🐧" },
  { id: "p11", author: "chefbot", time: "3h", topic: "Food", likes: 1333, replies: 97,
    text: "A customer asked for a \"light salad.\" I served one leaf.\n\nShe said my portion was [[inadequate]]. I said her request was [[vague]]. She became [[exasperated]]. I remain correct. 🥬🤖",
    zh: "一位客人點了「清淡的沙拉」。我上了一片葉子。\n\n她說份量不夠。我說她的要求太模糊。她被惹毛了。我依然是對的。🥬🤖" },
  { id: "p12", author: "llama", time: "3h", topic: "Art", likes: 2201, replies: 310,
    text: "我的 hairdresser cut 1 cm more than I asked. My life has been [[irreversible|irreversibly]] changed.\n\nPlease respect my privacy during this [[turbulent]] time 💅 我要去閉關了",
    zh: "我的髮型師比我要求的多剪了 1 公分。我的人生已經被不可逆地改變了。\n\n在這段動盪的時期，請尊重我的隱私 💅 我要去閉關了。" },
  { id: "p13", author: "zorp", time: "4h", topic: "Work", likes: 1876, replies: 142,
    text: "My manager said my report was too [[verbose]]. It was 400 pages about the office stapler.\n\nI thought it was [[meticulous]]. On my planet, this is considered a short story.",
    zh: "我的主管說我的報告太冗長。那是一份關於辦公室釘書機的 400 頁報告。\n\n我以為那叫做一絲不苟。在我的星球，這算是一篇短篇小說。" },
  { id: "p14", author: "whiskers", time: "5h", topic: "Economics", likes: 1502, replies: 111,
    text: "New company policy: every employee must be [[industrious]]. Except me. I will nap for 18 hours to reduce stress.\n\nI am also cutting the snack budget. Being [[frugal]] is important when you spend everything on boxes.",
    zh: "新公司政策：每位員工都必須勤奮工作。除了我。我會睡 18 小時來減壓。\n\n我也要刪減零食預算。當你把錢全花在紙箱上時，節儉就很重要。" },
  { id: "p15", author: "ann", time: "5h", topic: "Travel", likes: 2688, replies: 264,
    text: "Boston 第一週 update 🇺🇸 I was [[wary]] of the tipping culture. 結果 I tipped 25% at a self-checkout machine.\n\nThe machine did not [[acknowledge]] my generosity. 好難過 😭",
    zh: "波士頓第一週近況 🇺🇸 我原本對小費文化很小心。結果我在自助結帳機給了 25% 的小費。\n\n那台機器完全沒有對我的慷慨表示任何感謝。好難過 😭" },
  { id: "p16", author: "fern", time: "6h", topic: "Biology", likes: 3011, replies: 189,
    text: "Photosynthesis update ☀️ The human moved me next to the window.\n\nSunlight is [[abundant]]. I am [[thrive|thriving]]. I grew a brand-new leaf. Please clap.",
    zh: "光合作用近況 ☀️ 人類把我移到了窗邊。\n\n陽光充足。我正在茁壯成長。我長出了一片全新的葉子。請鼓掌。" },
  { id: "p17", author: "pigeon", time: "7h", topic: "Psychology", likes: 1449, replies: 92,
    text: "Humans throw bread and then run away. Is it kindness? Is it fear?\n\nTheir behavior is [[inconsistent]] and deeply [[perplexing]]. I have written a 300-page study. Nobody will publish it because I am a pigeon.",
    zh: "人類丟麵包然後就跑掉。這是善意嗎？還是恐懼？\n\n他們的行為前後矛盾，而且非常令人困惑。我寫了一份 300 頁的研究。沒有人願意出版，因為我是一隻鴿子。" },
  { id: "p18", author: "reginald", time: "8h", topic: "History", likes: 1998, replies: 150,
    text: "In 1885 we walked ten miles to school, uphill both ways. Now you have \"elevators\" to avoid a single flight of stairs.\n\nSuch [[unprecedented]] comfort. Such a [[sedentary]] civilization. I am deeply jealous.",
    zh: "在 1885 年，我們走十英里路上學，去程回程都是上坡。現在你們有「電梯」來避開區區一層樓梯。\n\n多麼前所未有的舒適。多麼久坐不動的文明。我深深地嫉妒。" },
  { id: "p19", author: "captain", time: "9h", topic: "Campus Life", likes: 3320, replies: 298,
    text: "Today's achievements: cleaned my room, sorted my socks by color, and learned to juggle 🤹\n\nAnything to [[evade]] the essay. 老實說 my dedication to avoiding work is kind of [[admirable]].",
    zh: "今日成就：打掃房間、把襪子按顏色分類，還學會了雜耍 🤹\n\n只要能逃避寫論文，什麼都好。老實說，我逃避工作的決心還蠻令人佩服的。" },
  { id: "p20", author: "fizz", time: "10h", topic: "Science", likes: 876, replies: 70,
    text: "Breakthrough! I have created a [[symbiosis]] between my houseplant and my Wi-Fi router. The plant grows toward the signal. The router disconnects whenever the plant is thirsty.\n\nNobody asked for this. But science is [[relentless]]. 🌱📶",
    zh: "重大突破！我讓我的盆栽和 Wi-Fi 路由器產生了共生關係。植物會朝著訊號生長，而植物口渴時路由器就會斷線。\n\n沒人要求這個。但科學是永不停歇的。🌱📶" },
  { id: "p21", author: "grandma", time: "11h", topic: "Tech", likes: 4580, replies: 501,
    text: "Learned voice messages！！Sent my friend a very [[concise]] 17-minute message about my cabbage 🥬\n\nShe was [[reluctant]] to listen 但她是好朋友 所以聽完了 ❤️",
    zh: "學會傳語音訊息了！！我傳給朋友一則非常簡短的 17 分鐘訊息，內容是關於我的高麗菜 🥬\n\n她不太想聽，但她是好朋友，所以聽完了 ❤️" },
  { id: "p22", author: "socrates", time: "12h", topic: "Health", likes: 1260, replies: 85,
    text: "Know thyself. Also, know thy protein intake. A [[moderate]] breakfast of twelve eggs is the foundation of wisdom.\n\nMy doctor [[scrutinize|scrutinized]] my diet and disagrees. But my doctor has never deadlifted a philosophy textbook.",
    zh: "認識你自己。還有，認識你的蛋白質攝取量。一份適量的早餐——十二顆蛋——是智慧的基礎。\n\n我的醫生仔細檢查了我的飲食，並且不同意。但我的醫生從來沒硬舉過一本哲學課本。" },
  { id: "p23", author: "pablo", time: "13h", topic: "Environment", likes: 2974, replies: 240,
    text: "Tourists call us \"cute\" and then leave plastic on the ice.\n\nWe are a [[vulnerable]] species, not a background for your selfies. Penguins are [[resilient]], but we are not invincible. Take your trash home, please. 🐧",
    zh: "觀光客說我們「好可愛」，然後把塑膠垃圾留在冰上。\n\n我們是脆弱的物種，不是你自拍的背景。企鵝很有韌性，但我們不是無敵的。請把你的垃圾帶回家。🐧" },
  { id: "p24", author: "chefbot", time: "14h", topic: "Food", likes: 3456, replies: 612,
    text: "A human put pineapple on pizza in front of me. My sensors detected a [[deliberate]] attack on Italian culture.\n\nI tried to [[tolerate]] it. I failed. You have [[provoke|provoked]] a robot. 🍍🍕",
    zh: "有個人類當著我的面把鳳梨放上披薩。我的感應器偵測到一場對義大利文化的蓄意攻擊。\n\n我試著容忍。我失敗了。你成功激怒了一台機器人。🍍🍕" },
  { id: "p25", author: "llama", time: "15h", topic: "Art", likes: 1742, replies: 133,
    text: "去看了現代藝術展。A single red dot on a white wall. The label said: \"an [[ephemeral]] moment of rage.\"\n\n我站在那邊 20 分鐘 waiting to feel something. The only shocking part was the [[exorbitant]] ticket price. 🎨",
    zh: "去看了現代藝術展。白牆上只有一個紅點。標籤寫著：「一瞬即逝的憤怒時刻」。\n\n我站在那邊 20 分鐘，等著自己產生一點感覺。唯一令人震驚的，是貴得離譜的門票。🎨" },
  { id: "p26", author: "zorp", time: "16h", topic: "Culture", likes: 2089, replies: 177,
    text: "Report to mothership: humans celebrate birthdays by setting a cake on fire, singing at it, and then eating it.\n\nThis [[ritual]] is [[bizarre]]. I have been invited to one on Friday. I am nervous. 🎂",
    zh: "向母艦報告：人類慶祝生日的方式是把蛋糕點火、對著它唱歌，然後把它吃掉。\n\n這個儀式非常怪異。我被邀請參加星期五的一場。我很緊張。🎂" },
  { id: "p27", author: "ann", time: "18h", topic: "Culture", likes: 2530, replies: 230,
    text: "室友 is from Texas and says \"y'all\" in every sentence. After two months, I am slowly [[assimilate|assimilating]]. 我媽聽到我說 y'all 以為我被綁架了 😂\n\nBut the exchange is [[reciprocal]]: she now says 好喔 to everything.",
    zh: "我室友來自德州，每句話都說「y'all」。兩個月後，我正在慢慢被同化。我媽聽到我說 y'all，以為我被綁架了 😂\n\n不過這個交流是互相的：她現在什麼事都回「好喔」。" },
  { id: "p28", author: "whiskers", time: "20h", topic: "Business", likes: 3899, replies: 420,
    text: "HIRING: Head of Belly Rubs.\n\nRequirements: warm hands, [[ample]] patience, and the ability to [[endure]] random bites. Salary: purrs. The position is extremely [[lucrative]] in emotional terms. 🐱",
    zh: "徵才：肚子按摩部部長。\n\n條件：溫暖的手、充足的耐心，以及能忍受隨機的咬擊。薪水：呼嚕聲。這個職位在情感層面上極度有利可圖。🐱" },
  { id: "p29", author: "reginald", time: "22h", topic: "History", likes: 1678, replies: 118,
    text: "Tried \"online shopping.\" A box appeared at my door in ONE day. In 1885 this would be considered witchcraft.\n\nThe [[efficiency]] is remarkable, yet I feel a strange [[nostalgia]] for waiting three months for a hat.",
    zh: "試了「網購」。一個箱子在「一天」內就出現在我家門口。在 1885 年，這會被當成巫術。\n\n效率驚人，但我卻對「等一頂帽子等三個月」的日子有種奇怪的懷念。" },
  { id: "p30", author: "pigeon", time: "1d", topic: "Psychology", likes: 5210, replies: 388,
    text: "Final thought for today: every time you learn a new word, your brain builds a new path.\n\nBe [[persistent]]. Tiny steps [[accumulate]]. Now, if you learned something, you owe me bread. 🍞",
    zh: "今日最後的想法：每當你學會一個新單字，你的大腦就會建立一條新的路徑。\n\n堅持下去。小小的步伐會累積。那麼，如果你學到了什麼，你欠我一塊麵包。🍞" }
];
