#!/usr/bin/env python3
"""Turn Codex difficulty scores into app data.

Usage: python3 scripts/import-scores.py [data-src/full_scores.csv]

Step 1 (TOEFL pack): re-levels the existing words in js/data/batch-*.js on one
global scale and writes js/data/levels.js. Level cut-offs are score thresholds
taken from the 1/3 and 2/3 points of every usable (non-review) score across
all word lists, so equal scores always get the same level and reruns are stable.
Cut-offs use only review_status = ai_initial_estimate rows; the TOEFL rows themselves accept any score.
"""
import json, re, subprocess, sys, collections
sys.path.insert(0, __import__("os").path.dirname(__file__))
from scorelib import load_rows, cutoffs, level_of

src = sys.argv[1] if len(sys.argv) > 1 else "data-src/full_scores.csv"
rows = load_rows(src)

t1, t2, n_scores = cutoffs(rows)
level = lambda s: level_of(s, t1, t2)

old = json.loads(subprocess.check_output(["node", "-e",
    'global.window={};const fs=require("fs");require("./js/data/characters.js");'
    'fs.readdirSync("js/data").filter(f=>/^batch-\\d+\\.js$/.test(f)).forEach(f=>require("./js/data/"+f));'
    "console.log(JSON.stringify(Object.entries(window.VOCAB).map(([k,v])=>[k,v.level])))"]))

toefl = {re.sub(r"\W", "", r["word"].lower()): r for r in rows if r["source_category"] == "TOEFL"}
out, kept, moved = {}, [], collections.Counter()
for key, lv in old:
    r = toefl.get(key.replace("_", ""))
    if not r or not r["initial_difficulty"]:
        kept.append(key)  # no trustworthy score: keep the hand-made level
        out[key] = [lv, lv, None]
        continue
    s = int(r["initial_difficulty"])
    out[key] = [level(s), lv, s]
    moved[(lv, level(s))] += 1

lines = ["// Generated by scripts/import-scores.py from data-src/full_scores.csv. Do not edit by hand.",
         f"// Level cut-offs (score): 1 <= {t1} < 2 <= {t2} < 3.  [level, levelOld, score]", "",
         "(function () {", "  var L = {"]
lines.append(",\n".join(f"    {k}: [{v[0]}, {v[1]}, {json.dumps(v[2])}]" for k, v in out.items()))
lines += ["  };", "  Object.keys(L).forEach(function (k) {",
          "    var v = window.VOCAB[k];", "    if (!v) return;",
          "    v.levelOld = L[k][1]; v.level = L[k][0]; if (L[k][2] !== null) v.diff = L[k][2];", "  });", "})();", ""]
open("js/data/levels.js", "w", encoding="utf-8").write("\n".join(lines))
print(f"cut-offs: level1 <= {t1}, level3 > {t2}  (from {n_scores} unique scores)")
print("new level counts:", dict(collections.Counter(v[0] for v in out.values())))
print("old -> new:", {f"{a}->{b}": n for (a, b), n in sorted(moved.items())})
print("kept old level (no usable score):", kept)
