#!/usr/bin/env python3
"""Turn Codex difficulty scores into app data.

Usage: python3 scripts/import-scores.py [data-src/full_scores.csv]

Step 1 (TOEFL pack): re-levels the existing words in js/data/batch-*.js on one
global scale and writes js/data/levels.js. Level cut-offs are score thresholds
taken from the 1/3 and 2/3 points of every usable (non-review) score across
all word lists, so equal scores always get the same level and reruns are stable.
Only rows with review_status = ai_initial_estimate are used.
"""
import csv, json, re, subprocess, sys, collections

src = sys.argv[1] if len(sys.argv) > 1 else "data-src/full_scores.csv"
rows = list(csv.DictReader(open(src, encoding="utf-8-sig")))
usable = [r for r in rows if r["review_status"] == "ai_initial_estimate" and r["initial_difficulty"]]

# One vote per (normalized word, meaning) so duplicated lists don't skew the cut-offs.
seen, scores = set(), []
for r in usable:
    k = (re.sub(r"\W", "", r["word"].lower()), r["meaning_zh"])
    if k not in seen:
        seen.add(k)
        scores.append(int(r["initial_difficulty"]))
scores.sort()
t1, t2 = scores[len(scores) // 3], scores[len(scores) * 2 // 3]  # level 1: <= t1, level 3: > t2
level = lambda s: 1 if s <= t1 else 3 if s > t2 else 2

old = json.loads(subprocess.check_output(["node", "-e",
    'global.window={};const fs=require("fs");require("./js/data/characters.js");'
    'fs.readdirSync("js/data").filter(f=>/^batch-\\d+\\.js$/.test(f)).forEach(f=>require("./js/data/"+f));'
    "console.log(JSON.stringify(Object.entries(window.VOCAB).map(([k,v])=>[k,v.level])))"]))

toefl = {re.sub(r"\W", "", r["word"].lower()): r for r in rows if r["source_category"] == "TOEFL"}
out, kept, moved = {}, [], collections.Counter()
for key, lv in old:
    r = toefl.get(key.replace("_", ""))
    if not r or r["review_status"] != "ai_initial_estimate" or not r["initial_difficulty"]:
        kept.append(key)  # no trustworthy score: keep the hand-made level
        out[key] = [lv, lv, None]
        continue
    s = int(r["initial_difficulty"])
    out[key] = [level(s), lv, s]
    moved[(lv, level(s))] += 1

lines = ["// Generated by scripts/import-scores.py from data-src/full_scores.csv. Do not edit by hand.",
         f"// Level cut-offs (score): 1 <= {t1} < 2 <= {t2} < 3.  [level, levelOld, score]", "",
         "(function () {", "  var L = {"]
lines.append(",\n".join(f"    {k}: [{v[0]}, {v[1]}, {json.dumps(v[2])}]" for k, v in out.items()))
lines += ["  };", "  Object.keys(L).forEach(function (k) {",
          "    var v = window.VOCAB[k];", "    if (!v) return;",
          "    v.levelOld = L[k][1]; v.level = L[k][0]; if (L[k][2] !== null) v.diff = L[k][2];", "  });", "})();", ""]
open("js/data/levels.js", "w", encoding="utf-8").write("\n".join(lines))
print(f"cut-offs: level1 <= {t1}, level3 > {t2}  (from {len(scores)} unique scores)")
print("new level counts:", dict(collections.Counter(v[0] for v in out.values())))
print("old -> new:", {f"{a}->{b}": n for (a, b), n in sorted(moved.items())})
print("kept old level (no usable score):", kept)
