// Generates js/data/kk.js (KK phonetic symbols) from the CMU Pronouncing Dictionary.
//   cd <scratch> && npm i cmu-pronouncing-dictionary
//   node scripts/make-kk.mjs <path-to-node_modules>
// KK conventions used by Taiwanese dictionaries: stress marks go at the start of the
// syllable (ˋ primary, ˏ secondary); ə/ʌ and ɚ/ɝ split by stress.
import fs from "fs";
import path from "path";
import { createRequire } from "module";

const modDir = process.argv[2];
const { dictionary } = await import(path.join(modDir, "cmu-pronouncing-dictionary", "index.js"));
const root = path.join(path.dirname(new URL(import.meta.url).pathname), "..");

global.window = {};
const require = createRequire(import.meta.url);
const dataDir = path.join(root, "js", "data");
require(path.join(dataDir, "characters.js"));
fs.readdirSync(dataDir).filter((f) => /^batch-\d+\.js$/.test(f)).forEach((f) => require(path.join(dataDir, f)));
const VOCAB = window.VOCAB;

// Pronunciation choices where the dictionary lists several and the part of speech decides.
// Values are CMU variant keys, or a full KK string when the dictionary has none that fits.
const OVERRIDE = JSON.parse(fs.readFileSync(path.join(root, "scripts", "kk-overrides.json"), "utf8"));

const VOWELS = { IY: "i", IH: "ɪ", EY: "e", EH: "ɛ", AE: "æ", AA: "ɑ", AO: "ɔ", OW: "o", UH: "ʊ", UW: "u", AY: "aɪ", AW: "aʊ", OY: "ɔɪ" };
const CONS = { CH: "tʃ", JH: "dʒ", SH: "ʃ", ZH: "ʒ", TH: "θ", DH: "ð", NG: "ŋ", Y: "j", HH: "h", R: "r",
  P: "p", B: "b", T: "t", D: "d", K: "k", G: "g", F: "f", V: "v", S: "s", Z: "z", M: "m", N: "n", L: "l", W: "w" };

// Legal English syllable onsets (maximal onset principle).
const ONSETS = new Set([
  "P R", "B R", "T R", "D R", "K R", "G R", "F R", "TH R", "SH R",
  "P L", "B L", "K L", "G L", "F L", "S L",
  "S P", "S T", "S K", "S M", "S N", "S W",
  "S P R", "S T R", "S K R", "S P L", "S K W",
  "T W", "D W", "K W", "G W", "TH W",
  "P Y", "B Y", "K Y", "G Y", "F Y", "V Y", "M Y", "HH Y", "N Y", "D Y", "T Y", "S P Y", "S K Y"
]);
function legalOnset(cluster) {
  if (cluster.length === 0) return true;
  if (cluster.length === 1) return cluster[0] !== "NG";
  return ONSETS.has(cluster.join(" "));
}

const LAX = new Set(["IH", "EH", "AE", "UH", "AH"]);

function toKK(arpabet) {
  let ph = arpabet.split(" ");
  const isV = (p) => /\d$/.test(p);
  // "ɚ" before a vowel is really "ə" + an "r" that starts the next syllable (tolerate → ˋtɑləˏret).
  const split = [];
  ph.forEach((p, i) => {
    if (/^ER\d$/.test(p) && ph[i + 1] && isV(ph[i + 1])) split.push(p === "ER1" ? "AH1" : "AH0", "R");
    else split.push(p);
  });
  ph = split;
  const vIdx = ph.map((p, i) => (isV(p) ? i : -1)).filter((i) => i >= 0);
  // Where each syllable starts.
  const starts = vIdx.map((vi, n) => {
    if (n === 0) return 0;
    const prev = vIdx[n - 1];
    const cluster = ph.slice(prev + 1, vi);
    let k = 0;
    // A short stressed vowel keeps a consonant after it (frustrate → ˋfrʌsˏtret).
    if (/[12]$/.test(ph[prev]) && LAX.has(ph[prev].slice(0, -1)) && cluster.length > 1) k = 1;
    while (!legalOnset(cluster.slice(k))) k++;
    return prev + 1 + k;
  });
  let out = "";
  ph.forEach((p, i) => {
    const s = starts.indexOf(i);
    if (s >= 0) {
      const stress = ph[vIdx[s]].slice(-1);
      if (stress === "1") out += "ˋ";
      else if (stress === "2") out += "ˏ";
    }
    if (isV(p)) {
      const base = p.slice(0, -1), st = p.slice(-1);
      if (base === "AH") out += st === "0" ? "ə" : "ʌ";
      else if (base === "ER") out += st === "0" ? "ɚ" : "ɝ";
      else out += VOWELS[base];
    } else {
      out += CONS[p];
    }
  });
  // A single-syllable word needs no stress mark.
  if (vIdx.length === 1) out = out.replace(/[ˋˏ]/g, "");
  // Secondary stress right before the main stress (in-sist, re-locate) is not written in KK.
  const st = vIdx.map((i) => ph[i].slice(-1));
  if (st[0] === "2" && st[1] === "1") out = out.replace(/^ˏ/, "");
  return "[" + out + "]";
}

const kk = {};
const missing = [];
const variants = [];
for (const w of Object.keys(VOCAB).sort()) {
  const o = OVERRIDE[w];
  if (o && o.startsWith("[")) { kk[w] = o; continue; }
  const key = o || w;
  const pron = dictionary[key];
  if (!pron) { missing.push(w); continue; }
  if (!o && dictionary[w + "(2)"]) variants.push(`${w} (${VOCAB[w].pos}): ${[w, w + "(2)", w + "(3)", w + "(4)"].filter((k) => dictionary[k]).map((k) => k + "=" + toKK(dictionary[k])).join("  ")}`);
  kk[w] = toKK(pron);
}

if (process.argv.includes("--report")) {
  console.log("VARIANTS (check part of speech):\n" + variants.join("\n"));
  console.log("\nMISSING:", missing.join(", ") || "none");
  process.exit(0);
}
if (missing.length) { console.error("Missing KK for: " + missing.join(", ")); process.exit(1); }
const body = "// KK phonetic symbols for every word, generated by scripts/make-kk.mjs from the CMU\n" +
  "// Pronouncing Dictionary (American English), with manual choices in scripts/kk-overrides.json.\n" +
  "window.KK = " + JSON.stringify(kk, null, 0).replace(/","/g, '",\n  "').replace("{", "{\n  ").replace(/}$/, "\n}") + ";\n";
fs.writeFileSync(path.join(dataDir, "kk.js"), body);
console.log("Wrote KK for " + Object.keys(kk).length + " words");
